- link:
    ~/.asdfrc: tools/asdf/asdfrc
    ~/.default-gems: tools/asdf/default-gems
    ~/.default-npm-packages: tools/asdf/default-npm-packages
    ~/.default-python-packages: tools/asdf/default-python-packages

- asdf:
    ### programming languages ###
    - plugin: python
      versions:
        - latest:3.9
    - plugin: ruby
      versions:
        - latest
    - plugin: nodejs
      versions:
        - latest:14
        - latest:16
        - latest
    - plugin: golang
      versions:
        - latest
    - plugin: rust
      versions:
        - stable
    - plugin: java
      versions:
        - latest:openjdk-11
        - latest:openjdk-17
    - plugin: scala
      versions:
        - latest
    - plugin: haskell
    - plugin: lua
    - plugin: luaJIT

    ### k8s cloud cluster provisioner ###
    - plugin: eksctl
      versions:
        - latest
    - plugin: aks-engine
    - plugin: kops
    ### k8s development tools ###
    - plugin: minikube # use zinit
    - plugin: skaffold # use zinit
    - plugin: draft
      versions:
        - latest
    - plugin: kubectl
      versions:
        - latest
    - plugin: kustomize
      versions:
        - latest
    - plugin: helm
      versions:
        - latest
    - plugin: helmfile # use zinit
    - plugin: stern # use zinit
    - plugin: fluxctl # use zinit
    - plugin: istioctl # use zinit
    - plugin: k9s # use zinit
    - plugin: kubeseal # use zinit
    - plugin: rancher

    ### Hashicorp ###
    - plugin: terraform
      versions:
        - latest
    - plugin: vault
      versions:
        - latest
    - plugin: packer
      versions:
        - latest
    - plugin: nomad
      versions:
        - latest
    - plugin: tflint # use zinit
    - plugin: terraform-docs # use zinit
    - plugin: terragrunt # use zinit

    ### development tools ###
    - plugin: hadolint # use zinit
    - plugin: shellcheck # use zinit
    - plugin: shfmt # use zinit
    - plugin: sops # use zinit
    - plugin: docker-slim # use zinit
    - plugin: docker-compose
    - plugin: docker-machine
    - plugin: protoc
      versions:
        - latest
    - plugin: direnv # use zinit
    - plugin: doctl # use zinit
    - plugin: mkcert # use zinit
    - plugin: sbt
      versions:
        - latest
    - plugin: groovy
    - plugin: gradle
    - plugin: maven
    - plugin: micronaut
    - plugin: sqlite
      versions:
        - latest
    - plugin: openresty
