- create:
    - ~/.config/htop/
    - ~/.config/pgcli/
    - ~/.config/youtube-dl/

- clean:
    - "~/"
    - "~/.config/bat"
    - "~/.config/btop"
    - "~/.config/htop/"
    - "~/.config/k9s"
    - "~/.config/lsd"
    - "~/.config/mc"
    - "~/.config/pgcli/"
    - "~/.config/pip"
    - "~/.config/vivid"
    - "~/.config/wireplumber"
    - "~/.config/youtube-dl/"

- link:
    ~/.digrc: misc/digrc
    ~/.gemrc: misc/gemrc
    ~/.mtrrc: misc/mtrrc
    ~/.wgetrc: misc/wgetrc
    ~/.curlrc: misc/curlrc
    ~/.psqlrc: misc/psqlrc
    ~/.myclirc: mycli/config
    ~/.Xresources: misc/Xresources
    ~/.ansiweatherrc: misc/ansiweatherrc
    ~/.config/bat: bat
    ~/.config/btop: btop
    ~/.config/htop/htoprc: misc/htoprc
    ~/.config/k9s: k9s
    ~/.config/lsd: lsd
    ~/.config/mc: mc
    ~/.config/pgcli/config: pgcli/config
    ~/.config/pip: pip
    ~/.config/vivid: vivid
    ~/.config/wireplumber: wireplumber
    ~/.config/youtube-dl/config: youtube-dl/config
