- shell:
    - [
        git clone https://gitlab.com/SpaceVim/SpaceVim.git ~/.config/SpaceVim,
        Installing SpaceVim,
      ]

- link:
    ~/.vim: ~/.config/SpaceVim
    ~/.config/nvim: ~/.config/SpaceVim
    ~/.SpaceVim.d: apps/vim/SpaceVim.d
