#!/bin/sh
# ~/.shell_functions
# Last Modified: 07/05/2015 05:33 AM

# fix slow gvim start
function gvim () { (/usr/bin/gvim -f "$@" &) }

# forwarded port ${2} on server to ${1} on the local (client)
# Usage: ssh_tunnel 5900 5901 mrtux@hdvietnam
function ssh_tunnel () {
    ssh -L ${1}:localhost:${2} -N -f ${3}
}

# create SOCKS 5 proxy on local (client) at port {1}
# Usage: create_ssh_proxy_at_port 9999 mrtux@hdvietnam
function create_ssh_proxy_at_port () {
    ssh -f -C2qTnN -D ${1} ${2}
}

# clipboard - put the arguments on the clipboard if we have xsel or xclip
# Usage : clipboard <something>
function clipboard () {
    if [ $DISPLAY ]; then
        { which xsel >/dev/null 2>/dev/null && echo -n "$@" | xsel; } \
        || { which xclip >/dev/null 2>/dev/null && echo -n "$@" | xclip; } \
        || echo "Haven't copied to the clipboard: no xsel or xclip" >&2
    else
        echo "Haven't copied to the clipboard: no \$DISPLAY" >&2
    fi
}

# bashlogger
function bashlogger () {
    script /tmp/log.txt
}

# End of file
