#!/bin/bash
# ~/.aliases

# use neovim instead vim
alias vim="nvim"
alias vi="nvim"

# quick up to parent directory
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# use aliases with sudo
alias sudo='sudo '

## colorize diff output
alias diff='colordiff'

alias mkdir='mkdir -p'
alias path='echo -e ${PATH//:/\\n}'

if [[ "$OSTYPE" = linux* ]] ; then
    # do not delete / or prompt if deleting more than 3 files at a time
    alias rm='rm -vI --preserve-root'

    alias df="df -kTh" # human-readable sizes
    alias wtf='dmesg | less' # debug
    alias free='free -m' # show sizes in MB
    alias less='less -r'
    alias more='less -r' # more is less

    # Get system memory, cpu usage, and gpu memory info quickly
    ## pass options to free
    alias meminfo='free -m -l -t'

    ## get top process eating memory
    alias psmem='ps auxf | sort -nr -k 4'
    alias psmem10='ps auxf | sort -nr -k 4 | head -10'

    ## get top process eating cpu
    alias pscpu='ps auxf | sort -nr -k 3'
    alias pscpu10='ps auxf | sort -nr -k 3 | head -10'

    ## Get server cpu info
    alias cpuinfo='lscpu'

    ## get GPU ram on desktop / laptop##
    alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'

    ## hardware info
    # lshw
    # dmidecode --type <keyword>
    #
    # Keyword     Types
    # ------------------------------
    # bios        0, 13
    # system      1, 12, 15, 23, 32
    # baseboard   2, 10
    # chassis     3
    # processor   4
    # memory      5, 6, 16, 17
    # cache       7
    # connector   8
    # slot        9


    # Type   Information
    # ----------------------------------------
    #    0   BIOS
    #    1   System
    #    2   Base Board
    #    3   Chassis
    #    4   Processor
    #    5   Memory Controller
    #    6   Memory Module
    #    7   Cache
    #    8   Port Connector
    #    9   System Slots
    #   10   On Board Devices
    #   11   OEM Strings
    #   12   System Configuration Options
    #   13   BIOS Language
    #   14   Group Associations
    #   15   System Event Log
    #   16   Physical Memory Array
    #   17   Memory Device
    #   18   32-bit Memory Error
    #   19   Memory Array Mapped Address
    #   20   Memory Device Mapped Address
    #   21   Built-in Pointing Device
    #   22   Portable Battery
    #   23   System Reset
    #   24   Hardware Security
    #   25   System Power Controls
    #   26   Voltage Probe
    #   27   Cooling Device
    #   28   Temperature Probe
    #   29   Electrical Current Probe
    #   30   Out-of-band Remote Access
    #   31   Boot Integrity Services
    #   32   System Boot
    #   33   64-bit Memory Error
    #   34   Management Device
    #   35   Management Device Component
    #   36   Management Device Threshold Data
    #   37   Memory Channel
    #   38   IPMI Device
    #   39   Power Supply

    ## Generate a Random MAC address
    alias random_mac="openssl rand -hex 6 | sed 's/\\(..\\)/\\1:/g; s/.$//'"

    ## Secure delete file
    alias secure-delete='shred -n 200 -z -u'

    ## Purging configuration files on Debian-based system
    alias agpc="sudo aptitude purge '~c'"

    # The Sliver Searcher (ag)
    # conflict with ubuntu plugin
    alias ag='command ag'
fi

# confirmation #
alias mv='mv -vi'
alias cp='cp -vi'
alias ln='ln -vi'

## this one saved by butt so many times ##
alias wget='wget -c'

## What's my public ip address?
#alias whatismyip="curl -s checkip.dyndns.org|sed -e 's/.*Current IP Address: //' -e 's/<.*$//'"
#alias whatismyip='wget ipinfo.io/ip -qO -'
alias whatismyip='curl ipinfo.io/ip'

# Using pew instead virtualenvwrapper
alias workon='pew workon'

# Use ptpython inside virtualenv
alias ptpython="python -m ptpython"
alias ptpy2="python2 -m ptpython"
alias ptpy3="python3 -m ptpython"

# SSH without HostKeyChecking and KnownHosts
alias tssh="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

### BENCHMARK DISK IO ###
alias fio-r='fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=fio --filename=fio --bs=4k --iodepth=64 --size=4G --readwrite=randread'
alias fio-w='fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=fio --filename=fio --bs=4k --iodepth=64 --size=4G --readwrite=randwrite'
alias fio-rw='fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=fio --filename=fio --bs=4k --iodepth=64 --size=4G --readwrite=randrw --rwmixread=75'

### Docker aliases ###
# Stop all running containers
alias dsa='docker stop $(docker ps -a -q)'
# remove all containers, even stopped ones
alias drmc='docker rm $(docker ps -aq)'
# Delete all existing images
alias drmi='docker image prune --all'
# Volume cleanup
alias dvc="docker volume ls -qf dangling=true | xargs -r docker volume rm"

alias tf="terraform"

### Kubernetes aliases ###
alias kgg="gcloud config configurations activate default && kubectl config use-context gke-labs"
alias kmini="kubectl config use-context minikube"

# End of file
