#!/usr/bin/env bash
# ~/.exports

# shell history tweaks
export SAVEHIST=10000                           # Remember about a years worth of history (AWESOME)
export HISTSIZE=10000                           # shell history will save N commands
export HISTFILESIZE=${HISTSIZE}                 # shell will remember N commands


if [[ "$OSTYPE" = linux* ]] ; then
    ### Setup PATH ###
    export MYBIN=$HOME/.local/bin                  # user binaries
    export CARGOBIN=$HOME/.cargo/bin               # Rust cargo
    export GOPATH=$HOME/.go                        # gocode
    export GOROOT=/usr/local/go                    # golang
    export TFENV=$HOME/.tfenv/bin                  # tfenv
    export YARNBIN=$(yarn global bin)              # yarn

    # My custom path
    export MYPATH=${MYBIN}:${TFENV}:${CARGOBIN}:${GOPATH}/bin:${YARNBIN}

    # Add directory to $PATH if it's not already there
    if [[ ":$PATH:" != *":${MYPATH}:"* ]]; then PATH=${MYPATH}:$PATH; fi

    ### virtualenv ###
    export WORKON_HOME=$HOME/.local/share/virtualenvs
    # nmap
    export NMAP_PRIVILEGED=""

    # minicom
    export MINICOM="-m -c on"

    # fix broken theme of LibreOffice in GTK+ 3.0
    export SAL_USE_VCLPLUGIN=gtk
    # mtr options
    export MTR_OPTIONS="-4 --no-dns --udp"

    # Setup Input Method
    export XMODIFIERS="@im=ibus"
    export GTK_IM_MODULE=ibus
    export QT_IM_MODULE=ibus
    export QT4_IM_MODULE=ibus

    # Setting locales
    export LC_ALL=en_US.UTF-8
    export LANGUAGE=en_US.UTF-8
    export LANG=en_US.UTF-8

    export BROWSER="firefox -new-tab %s"
    export EDITOR="vim"
    export USE_EDITOR=$EDITOR
    export VISUAL=$EDITOR
fi

# Color man pages
export PAGER='less'
unset LESSCHARSET # Fix manpages looking funky
export LESS='-i -n -w  -z-4 -g -M -X -F -R'

# Less Colors for Man Pages: Solarized Dark
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

# export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
# export LESS_TERMCAP_md=$'\E[01;31m'       # begin bold
# export LESS_TERMCAP_me=$'\E[0m'           # end mode
# export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
# export LESS_TERMCAP_so=$'\E[0;37;102m'    # begin standout-mode - info box
# export LESS_TERMCAP_ue=$'\E[0m'           # end underline
# export LESS_TERMCAP_us=$'\E[04;32m'       # begin underline

# End of file
