#!/usr/bin/env bash
# ~/.exports

# shell history tweaks
export SAVEHIST=10000                           # Remember about a years worth of history (AWESOME)
export HISTSIZE=10000                           # shell history will save N commands
export HISTFILESIZE=${HISTSIZE}                 # shell will remember N commands

# https://bugzilla.gnome.org/show_bug.cgi?id=772919
# https://eklitzke.org/down-the-ssh-auth-sock-rabbit-hole-a-gnome-adventure
export GSM_SKIP_SSH_AGENT_WORKAROUND=1


export BIN_DIR=$HOME/.local/bin                 # user binaries

if [[ "$OSTYPE" = darwin* ]] ; then
    export PATH=$BIN_DIR:$PATH
else
    ### Setup PATH ###
    export CARGO=$HOME/.cargo/bin               # Rust cargo
    export CABAL=$HOME/.cabal/bin               # Haskell cabal
    export POETRY=$HOME/.poetry/bin             # poetry
    # shellcheck disable=SC2155
    export YARNBIN=$(yarn global bin)           # yarn
    export KREW_ROOT=$HOME/.krew                # krew

    # My custom path
    MYPATH=("${BIN_DIR}"
            "${POETRY}"
            "${KREW_ROOT}/bin"
            "${CARGO}"
            "${CABAL}"
            "${YARNBIN}")

    # Add directory to $PATH if its not already there
    for p in "${MYPATH[@]}"; do
      case ":$PATH:" in
        *":$p:"*) :;;
        *) PATH="$p:$PATH";;
      esac
    done

    ### virtualenv ###
    export WORKON_HOME=$HOME/.local/share/virtualenvs
    # nmap
    export NMAP_PRIVILEGED=""

    # minicom
    export MINICOM="-m -c on"

    # fix broken theme of LibreOffice in GTK+ 3.0
    export SAL_USE_VCLPLUGIN=gtk
    # mtr options
    export MTR_OPTIONS="-4 --no-dns --udp"

    # Setup Input Method
    export MY_INPUT_METHOD="ibus"
    export XMODIFIERS=${XMODIFIERS:-@im=${MY_INPUT_METHOD}}
    export GTK_IM_MODULE=${GTK_IM_MODULE:-${MY_INPUT_METHOD}}
    export QT_IM_MODULE=${QT_IM_MODULE:-${MY_INPUT_METHOD}}
    export QT4_IM_MODULE=${QT4_IM_MODULE:-${MY_INPUT_METHOD}}
    export CLUTTER_IM_MODULE=${CLUTTER_IM_MODULE:-${MY_INPUT_METHOD}}

    # Setting locales
    export LC_ALL=en_US.UTF-8
    export LANGUAGE=en_US.UTF-8
    export LANG=en_US.UTF-8

    export BROWSER="firefox -new-tab %s"
fi

# Use nvim instead vi(m)
export EDITOR="nvim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR
export KUBE_EDITOR="code --wait"

export BAT_THEME="TwoDark"

# Color man pages
export PAGER='less'
unset LESSCHARSET # Fix manpages looking funky
export LESS='-i -n -w -z4 -g -M -S -R -X -F'

# Less Colors for Man Pages: Solarized Dark
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

# export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
# export LESS_TERMCAP_md=$'\E[01;31m'       # begin bold
# export LESS_TERMCAP_me=$'\E[0m'           # end mode
# export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
# export LESS_TERMCAP_so=$'\E[0;37;102m'    # begin standout-mode - info box
# export LESS_TERMCAP_ue=$'\E[0m'           # end underline
# export LESS_TERMCAP_us=$'\E[04;32m'       # begin underline

# End of file
