#!/usr/bin/env bash

set -e

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

META_DIR="meta"
CONFIG_DIR="configs"
PLUGINS_DIR="plugins"
PROFILES_DIR="profiles"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASE_DIR}"
git submodule update --init --recursive --remote

CONFIGS="$(find ${META_DIR}/${CONFIG_DIR}/ -type f -name "*.yaml" -exec basename -s "${CONFIG_SUFFIX}" {} \;)"

"${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -c "${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}"

for config in ${CONFIGS} "${@}"; do
  echo -e "\nConfigure $config"
  "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -d "${BASE_DIR}" \
    -c "${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}"
done
