- defaults:
    link:
      force: true
      create: true
      relink: true
      ignore-missing: true

- clean:
    - "~"
    - "~/.gnupg"
    - "~/.config"
    - "~/.local/bin"
    - "~/.config/htop"
    - "~/.config/pgcli"
    - "~/.config/youtube-dl"
