- defaults:
    link:
      force: true
      backup: true
      create: true
      relink: true
      ignore-missing: true

- clean:
    - "~"
    - "~/.ssh"
    - "~/.ssh/config.d"
    - "~/.gnupg"
    - "~/.config"
    - "~/.local/bin"
    - "~/.config/htop"
    - "~/.config/pgcli"
    - "~/.config/youtube-dl"
