if [ $commands[kubectl] ]; then
  source <(kubectl completion zsh)
  alias k="kubectl"
  alias kg="kubectl get"
  alias ke="kubectl edit"
  alias ked="kubectl edit deployment"
  alias kecm="kubectl edit configmap"
  alias kes="kubectl edit svc"

  alias kn="kubectl get nodes"
  alias ks="kubectl get svc"
  alias kr="kubectl get rs"
  alias krc="kubectl get rc"
  alias kd="kubectl get deployment"
  alias kp="kubectl get pods"
  alias kpa="kubectl get pods --all-namespaces"
  alias kk="kubectl get svc,deployment,pods"

  alias dsn="kubectl describe node"
  alias dss="kubectl describe svc"
  alias dsr="kubectl describe rs"
  alias dsd="kubectl describe deployment"
  alias dsp="kubectl describe pod"

  alias kl="kubectl logs --tail=50 --follow"
  alias kx="kubectl exec"
  alias xx="kubectl exec -ti"
  alias kcf="kubectl create -f"
  alias kdf="kubectl delete -f"
  alias ddr="kubectl delete rs"
  alias ddd="kubectl delete deployment"
  alias dds="kubectl delete svc"
  alias ddp="kubectl delete pod"
  alias kcm="kubectl create configmap"
  alias kdm="kubectl delete configmap"
  alias khpa="kubectl get hpa"
fi
