#!/usr/bin/env python3
"""Automatically set commit author based on repo URL."""

# require: gitpython
import os
import sys
import git
import configparser

repo = git.Repo(os.getcwd())

# Don't do anything if an identity is already configured in this
# repo's .git/config
config = repo.config_reader(config_level="repository")

try:
    # The value of user.email is non-empty, stop here
    if config.get_value("user", "email"):
        sys.exit(0)
except (configparser.NoSectionError, configparser.NoOptionError):
    # Section or option does not exist, continue
    pass

origin = repo.remote("origin")
if not origin:
    print("** Failed to detect remote origin, identity not updated! **")
    sys.exit(0)


# This is where you adjust the code to fit your needs
if any(s in origin.url for s in ["inspectorio"]):
    name = "Thuan Duong"
    email = "thuan@inspectorio.com"
    gpgsign = "true"
else:
    print("** Use default identity **")
    name = "Thuan Duong"
    email = "thuandt26@gmail.com"
    gpgsign = "true"
    sys.exit(0)

# Write the option to .git/config
config = repo.config_writer()
config.set_value("user", "email", email)
config.set_value("user", "name", name)
config.set_value("commit", "gpgsign", gpgsign)
config.release()
print("** User identity for this repository set to '%s <%s> **'" % (name, email))
