# Btop Selenized Dark theme
# Canonical palette by Jan Warchol

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#103c48"

# Main text color
theme[main_fg]="#adbcbc"

# Title color for boxes
theme[title]="#cad8d9"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#4695f7"

# Background color of selected items
theme[selected_bg]="#184956"

# Foreground color of selected items
theme[selected_fg]="#cad8d9"

# Color of inactive/disabled text
theme[inactive_fg]="#72898f"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#41c7b9"

# Cpu box outline color
theme[cpu_box]="#2d5b69"

# Memory/disks box outline color
theme[mem_box]="#2d5b69"

# Net up/down box outline color
theme[net_box]="#2d5b69"

# Processes box outline color
theme[proc_box]="#2d5b69"

# Box divider line and small boxes line color
theme[div_line]="#2d5b69"

# Temperature graph colors
theme[temp_start]="#41c7b9"
theme[temp_mid]="#db9d26"
theme[temp_end]="#fa5750"

# CPU graph colors
theme[cpu_start]="#75b938"
theme[cpu_mid]="#ed8649"
theme[cpu_end]="#fa5750"

# Mem/Disk free meter
theme[free_start]="#184956"
theme[free_mid]=""
theme[free_end]="#75b938"

# Mem/Disk cached meter
theme[cached_start]="#184956"
theme[cached_mid]=""
theme[cached_end]="#4695f7"

# Mem/Disk available meter
theme[available_start]="#184956"
theme[available_mid]=""
theme[available_end]="#41c7b9"

# Mem/Disk used meter
theme[used_start]="#184956"
theme[used_mid]=""
theme[used_end]="#ed8649"

# Download graph colors
theme[download_start]="#184956"
theme[download_mid]="#4695f7"
theme[download_end]="#af88e6"

# Upload graph colors
theme[upload_start]="#184956"
theme[upload_mid]="#f275be"
theme[upload_end]="#fa5750"
