#!/usr/bin/zsh
# ~/.zprofile
# Last Modified: 12/04/2012 05:43:56 AM

if [ -f ~/.zshrc ]; then
       source ~/.zshrc
fi

### START-Keychain ###
# Let re-use ssh-agent and/or gpg-agent between logins
keychain $HOME/.ssh/id_rsa
source $HOME/.keychain/$HOSTNAME-sh
source $HOME/.keychain/$HOSTNAME-sh-gpg
### END-Keychain ###

_byobu_sourced=1 . /usr/bin/byobu-launch
