if [[ "$OSTYPE" = linux* ]] ; then
    # https://github.com/robbyrussell/oh-my-zsh/issues/1433
    DEBIAN_PREVENT_KEYBOARD_CHANGES=yes
    systemctl --user import-environment PATH
fi

source ~/.exports
