#!/usr/bin/env zsh
# ~/.zshrc

# zinit
export ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)/completions"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
[ ! -f "$(dirname $ZINIT_HOME)/completions/_zinit" ] && ln -sf "$ZINIT_HOME/_zinit" "$(dirname $ZINIT_HOME)/completions/_zinit"

source "${ZINIT_HOME}/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Create cache and completions dir and add to $fpath
[ ! -d "$ZSH_CACHE_DIR/completions"] && mkdir -p "$ZSH_CACHE_DIR/completions"
(( ${fpath[(Ie)"$ZSH_CACHE_DIR/completions"]} )) || fpath=("$ZSH_CACHE_DIR/completions" $fpath)

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)
zinit light zdharma-continuum/zinit-annex-meta-plugins
zinit lucid light-mode skip"dircolors-material" for annexes zsh-users+fast console-tools

# direnv workaround for instant-prompt
# https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-initialize-direnv-when-using-instant-prompt
(( ${+commands[direnv]} )) && emulate zsh -c "$(direnv export zsh)"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# direnv workaround for instant-prompt
(( ${+commands[direnv]} )) && emulate zsh -c "$(direnv hook zsh)"

# disable C-s stopping receiving keyboard signals.
# stty start undef
# stty stop undef

# OMZ libs and plugins
zinit wait lucid light-mode for \
  OMZL::clipboard.zsh \
  OMZL::completion.zsh \
  OMZL::directories.zsh \
  OMZL::functions.zsh \
  OMZL::git.zsh \
  OMZL::grep.zsh \
  OMZL::history.zsh \
  OMZL::key-bindings.zsh \
  OMZL::misc.zsh \
  OMZL::termsupport.zsh \
  OMZL::theme-and-appearance.zsh \
  OMZP::mise \
  OMZP::gcloud \
  atload"unalias grv" OMZP::git

# For GNU ls (the binaries can be gls, gdircolors, e.g. on OS X when installing the
# coreutils package from Homebrew or using https://github.com/ogham/exa)
zinit wait lucid light-mode reset \
  atclone'dircolors -b dircolors.ansi-dark > clrs.zsh' \
  atpull'%atclone' pick'clrs.zsh' nocompile'!' \
  atload'zstyle ":completion:*" list-colors "${(s.:.)LS_COLORS}"' \
  for seebi/dircolors-solarized

zinit wait lucid light-mode depth=1 for \
  OMZP::gpg-agent \
  OMZP::ansible \
  OMZP::azure \
  OMZP::aws \
  OMZP::extract \
  OMZP::encode64 \
  OMZP::nmap \
  OMZP::kubectl \
  OMZP::helm \
  OMZP::minikube \
  OMZP::rsync \
  OMZP::sudo \
  OMZP::systemd \
  OMZP::suse \
  OMZP::npm \
  OMZP::yarn \
  OMZP::gitignore \
  chrissicool/zsh-256color \
  djui/alias-tips \
  jreese/zsh-titles \
  amstrad/oh-my-matrix \
  micha/resty \
  changyuheng/fz \
  thuandt/zsh-terraform \
  thuandt/zsh-vault

zinit pack"bgn-binary+keys" for fzf
# z
zinit wait lucid light-mode cp='z.sh -> z' pick'z' src'z.sh' for rupa/z

# enhancd with fzf
zinit wait lucid light-mode pick'init.sh' nocompletions for b4b4r07/enhancd

# direnv
zinit wait lucid light-mode as'null' from'gh-r' \
  mv'direnv* -> direnv' \
  sbin'direnv' src'zhook.zsh' \
  atclone'./direnv hook zsh > zhook.zsh' \
  atpull'%atclone' for direnv/direnv

# generate auto completion from program
zinit wait lucid light-mode pick'/dev/null' for \
  id-as'argocd-completion' atload'[ $commands[argocd] ] && source <(argocd completion zsh)' zdharma-continuum/null \
  id-as'argocd-image-updater-completion' atload'[ $commands[argocd-image-updater] ] && source <(argocd-image-updater completion zsh)' zdharma-continuum/null \
  id-as'caddy-completion' atload'[ $commands[caddy] ] && source <(caddy completion zsh)' zdharma-continuum/null \
  id-as'checkov-completion' atload'[ $commands[checkov] ] && source <(register-python-argcomplete checkov)' zdharma-continuum/null \
  id-as'cloud-sql-proxy-completion' atload'[ $commands[cloud-sql-proxy] ] && source <(cloud-sql-proxy completion zsh)' zdharma-continuum/null \
  id-as'cmctl-completion' atload'[ $commands[cmctl] ] && source <(cmctl completion zsh)' zdharma-continuum/null \
  id-as'cosign-completion' atload'[ $commands[cosign] ] && source <(cosign completion zsh)' zdharma-continuum/null \
  id-as'cue-completion' atload'[ $commands[cue] ] && source <(cue completion zsh)' zdharma-continuum/null \
  id-as'docker-completion' atload'[ $commands[docker] ] && source <(docker completion zsh)' zdharma-continuum/null \
  id-as'exercism-completion' atload'[ $commands[exercism] ] && source <(exercism completion zsh)' zdharma-continuum/null \
  id-as'flyctl-completion' atload'[ $commands[flyctl] ] && source <(flyctl completion zsh)' zdharma-continuum/null \
  id-as'gh-completion' atload'[ $commands[gh] ] && source <(gh completion -s zsh)' zdharma-continuum/null \
  id-as'glab-completion' atload'[ $commands[glab] ] && source <(glab completion -s zsh) && compdef _glab glab' zdharma-continuum/null \
  id-as'hugo-completion' atload'[ $commands[hugo] ] && source <(hugo completion zsh)' zdharma-continuum/null \
  id-as'infracost-completion' atload'[ $commands[infracost] ] && infracost completion --shell zsh >! ${ZSH_CACHE_DIR}/completions/_infracost' zdharma-continuum/null \
  id-as'k6-completion' atload'[ $commands[k6] ] && source <(k6 completion zsh)' zdharma-continuum/null \
  id-as'k9s-completion' atload'[ $commands[k9s] ] && source <(k9s completion zsh)' zdharma-continuum/null \
  id-as'stern-completion' atload'[ $commands[stern] ] && source <(stern --completion=zsh)' zdharma-continuum/null \
  id-as'opa-completion' atload'[ $commands[opa] ] && source <(opa completion zsh)' zdharma-continuum/null \
  id-as'pipenv-completion' atload'[ $commands[pipenv] ] && eval $(register-python-argcomplete pipenv)' zdharma-continuum/null \
  id-as'pipx-completion' atload'[ $commands[pipx] ] && eval $(register-python-argcomplete pipx)' zdharma-continuum/null \
  id-as'poetry-completion' atload'[ $commands[poetry] ] && poetry completions zsh >! ${ZSH_CACHE_DIR}/completions/_poetry' zdharma-continuum/null \
  id-as'yq-completion' atload'[ $commands[yq] ] && source <(yq completion zsh)' zdharma-continuum/null

# ansiweather
zinit wait lucid light-mode pick'/dev/null' sbin'ansiweather' for fcambus/ansiweather

# color logger
zinit wait lucid light-mode src'color-logger.bash' pick'/dev/null' for swyckoff/color-logger-bash

# manydots-magic
zinit wait lucid light-mode for \
  pick'manydots-magic' knu/zsh-manydots-magic

# zsh-diff-so-fancy
zplugin wait lucid light-mode \
  pick"bin/git-dsf" \
  sbin'bin/git-dsf' \
  sbin'bin/diff-so-fancy' \
  as"program" for thuandt/zsh-diff-so-fancy

zinit wait lucid light-mode for \
  zchee/zsh-completions \
  gradle/gradle-completion \
  arzzen/calc.plugin.zsh

# https://github.com/zsh-users/zsh-autosuggestions/issues/642#issuecomment-2136812444
# autosuggest-accept: Accepts the current suggestion.
# autosuggest-execute: Accepts and executes the current suggestion.
# autosuggest-clear: Clears the current suggestion.
# autosuggest-fetch: Fetches a suggestion (works even when suggestions are disabled).
# autosuggest-disable: Disables suggestions.
# autosuggest-enable: Re-enables suggestions.
# autosuggest-toggle: Toggles between enabled/disabled suggestions.
zinit lucid light-mode depth=1 for \
  atload"_zsh_autosuggest_start; \
        ZSH_AUTOSUGGEST_STRATEGY=(history completion) \
        ZSH_AUTOSUGGEST_MANUAL_REBIND=0 \
        bindkey '^ ' autosuggest-execute" \
    zsh-users/zsh-autosuggestions \
  jeffreytse/zsh-vi-mode \
  thuandt/zsh-config

zinit load 'zsh-users/zsh-history-substring-search'
zinit ice wait atload'_history_substring_search_config'

### THEME ###
zinit lucid light-mode nocd depth='1' atload'!source ~/.p10k.zsh; _p9k_precmd' for romkatv/powerlevel10k

# Username completion.
# Delete old definitions
zstyle -d users
# For SSH and related stuff, use remote users set in SSH configuration, plus root
zstyle ':completion:*:*:(ssh|scp|rsync|mosh|slogin|rclone):*' users root $(awk '$1 == "User" { print $2 }' ~/.ssh/config ~/.ssh/config.d/* | sort -u)
# For everything else, use non-system users from /etc/passwd, plus root
zstyle ':completion:*:*:*:*' users root $(awk -F: '$3 >= 1000 && $3 < 65000 { print $1 }' /etc/passwd)

# ssh hostname completion
# https://serverfault.com/a/170481
h=()
if [[ -r ~/.ssh/config ]]; then
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/config ~/.ssh/config.d/* 2>/dev/null)"}:#Host *}#Host }:#*[*?]*})
fi
# HashKnownHosts must be disabled
# if [[ -r ~/.ssh/known_hosts ]]; then
#   h=($h ${${${(f)"$(cat ~/.ssh/known_hosts{,2} || true)"}%%\ *}%%,*}) 2>/dev/null
# fi
if [[ $#h -gt 0 ]]; then
  zstyle ':completion:*:(ssh|scp|rsync|lftp|ftp|mosh|slogin|rclone):*' hosts $h
fi

# Hostname completion
zstyle -e ':completion:*:hosts' hosts 'reply=(${=${(f)"$(grep -v 0.0.0.0 /etc/hosts)"}%%\#*})'

# Prettify path
if [ -n "$($SHELL -c "echo $ZSH_VERSION")" ]; then
  # remove duplicates in zsh path
  # https://til.hashrocket.com/posts/7evpdebn7g-remove-duplicates-in-zsh-path
  # shellcheck disable=SC2034
  typeset -aU path
# elif [ -n "$($SHELL -c "echo $BASH_VERSION")" ]; then
else
  PATH="$(perl -e 'print join(":", grep { not $seen{$_}++ } split(/:/, $ENV{PATH}))')"
fi

# Tilix
# https://github.com/gnunn1/tilix/wiki/VTE-Configuration-Issue
if [[ "$OSTYPE" == linux* ]]; then
  if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
    source /etc/profile.d/vte.sh
  fi
fi

# Don't store failed command to history
# http://scarff.id.au/blog/2019/zsh-history-conditional-on-command-success/
zshaddhistory() {
  whence ${${(z)1}[1]} >| /dev/null || return 1
  local line cmd
  line=${1%%$'\n'}
  cmd=${line%% *}
  [[ ${#line} -ge 5 \
    && ${cmd} != (apm|base64|bzip2|cal|calc|cat|cd|chmod|cp|curl|cvs|date|df|diff|dig|disklabel|dmesg|doas|du|e|egrep|enc|ent|exiftool|f|fdisk|feh|file|find|gimp|git|gpg|grep|hdiutil|head|hostname|ifconfig|kill|less|ls|mail|make|man|mkdir|mount|mpv|mv|nc|openssl|patch|pdf|pdfinfo|pgrep|ping|pkg_info|pkill|ps|rcctl|rm|rsync|scp|scrot|set|sha256|sort|srm|ssh|stat|strip|sudo|sysctl|tar|tmux|top|umount|uname|unzip|uptime|useradd|vlc|vi|vim|wc|wget|which|whoami|whois|wireshark|xclip|xxd|youtube-dl)
  ]]
}

# -q is for quiet; actually run all the `compdef's saved before `compinit` call
# (`compinit' declares the `compdef' function, so it cannot be used until
# `compinit' is ran; Zinit solves this via intercepting the `compdef'-calls and
# storing them for later use with `zinit cdreplay')

zinit cdreplay -q

# p10k instant prompt
(( ! ${+functions[p10k]} )) || p10k finalize

# Clear screen
# clear

# End of ~/.zshrc
