#!/bin/zsh
# ~/.zshrc
# Last Modified: 26/12/2013 07:40 PM

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="bira"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=( battery bundler colorize command-not-found common-aliases cp debian
          emoji-clock encode64 extract gem git git-extras git-flow
          git-remote-branch gitignore gpg-agent heroku history
          history-substring-search mercurial mosh pip python rails rake rsync
          ruby rvm safe-paste screen ssh-agent sublime sudo svn systemadmin
          tmux tmuxinator urltools virtualenv virtualenvwrapper vundle
          wakeonlan websearch )

##### tmux #####
# Automatically start tmux
ZSH_TMUX_AUTOSTART=false
# Only autostart once. If set to false, tmux will attempt to
# autostart every time your zsh configs are reloaded.
ZSH_TMUX_AUTOSTART_ONCE=true
# Automatically connect to a previous session if it exists
ZSH_TMUX_AUTOCONNECT=true
# Set term to screen or screen-256color based on current terminal support
ZSH_TMUX_FIXTERM=true
# The TERM to use for non-256 color terminals.
# Tmux states this should be screen, but you may need to change it on
# systems without the proper terminfo
ZSH_TMUX_FIXTERM_WITHOUT_256COLOR="screen"
# The TERM to use for 256 color terminals.
# Tmux states this should be screen-256color, but you may need to change it on
# systems without the proper terminfo
ZSH_TMUX_FIXTERM_WITH_256COLOR="screen-256color"

# source oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Customize to your needs...

##### ZSH OPTIONS #####
# Changing Directories
setopt AUTO_CD           # why would you type 'cd dir' if you could just type 'dir'?
setopt AUTO_NAME_DIRS    # This will use named dirs when possible
setopt CDABLE_VARS
setopt PUSHD_IGNORE_DUPS # this will ignore multiple directories for the stack
setopt PUSHD_MINUS
setopt ALWAYS_TO_END
unsetopt LIST_AMBIGUOUS
setopt COMPLETE_IN_WORD  # If unset, the cursor is set to the end of the word if
                         # completion is started. Otherwise it stays there and
                         # completion is done from both ends.
setopt EXTENDED_GLOB     # I don't know why I never set this before.
setopt NO_BEEP           # beeps are annoying
setopt NO_CASE_GLOB      # Case insensitive globbing
setopt NO_CLOBBER        # Keep echo "station" > station from clobbering station
setopt NO_FLOW_CONTROL   # If I could disable Ctrl-s completely I would!
setopt NO_HUP
setopt NUMERIC_GLOB_SORT # Be Reasonable!
setopt RM_STAR_WAIT      # 10 second wait if you do something that will delete everything
setopt ZLE               # use magic (this is default, but it can't hurt!)

# History Tweak
setopt APPEND_HISTORY         # Don't overwrite, append!
unsetopt EXTENDED_HISTORY     # Save the time and how long a command ran
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS   # Even if there are commands inbetween commands that are the same, still only save the last one
setopt HIST_IGNORE_DUPS       # If I type cd and then cd again, only save the last one
setopt HIST_IGNORE_SPACE      # If a line starts with a space, don't save it.
setopt HIST_NO_STORE
setopt HIST_REDUCE_BLANKS     # Pretty    Obvious.  Right?
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY            # When using a hist thing, make a newline show the change before executing it.
unsetopt SHARE_HISTORY        # Killer: share history between multiple shells

# Color listing
eval $(dircolors ~/.dir_colors)
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# Source shell_alias, shell_env, shell_functions
[[ -s "$HOME/.shell_env" ]] && source "$HOME/.shell_env"
[[ -s "$HOME/.shell_aliases" ]] && source "$HOME/.shell_aliases"
[[ -s "$HOME/.shell_functions" ]] && source "$HOME/.shell_functions"

##### Ruby RVM #####
# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

##### virtualenvwrapper #####
[[ -s /usr/local/bin/virtualenvwrapper.sh ]] && source /usr/local/bin/virtualenvwrapper.sh

##### Google Cloud SDK #####
autoload bashcompinit
bashcompinit
source /home/mrtux/app/google-cloud-sdk/arg_rc

# Automatically run ls after every cd
function chpwd() {
    emulate -L zsh
    ls -a
}

# automatically source zshrc in all open terminals
trap "source ~/.zshrc && rehash" USR1

# End of ~/.zshrc