#=============================================================================
# init.toml --- configuration for SpaceVim
#=============================================================================

# All SpaceVim option below [option] section
[options]
    automatic_update = 1

    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "NeoSolarized"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    guifont = "CaskaydiaCove Nerd Font:h11"
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode_symbols = true
    filetree_direction = "left"

    # Enable Vim compatible mode, avoid changing origin Vim key bindings
    vimcompatible = true

[[layers]]
    name = "colorscheme"

[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = "fzf"

[[layers]]
    name = "checkers"

[[layers]]
    name = "git"

[[layers]]
    name = "sudo"

[[layers]]
    name = "tmux"

[[layers]]
    name = "tools#zeal"

[[layers]]
    name = "lang#python"

[[layers]]
    name = "lang#dockerfile"

[[layers]]
    name = "lang#sh"

[[layers]]
    name = "lang#go"

[[layers]]
    name = "lang#groovy"

