override.monitor.alsa.rules = [
  ### Enable ACP and disable UCM for all ALSA cards ###
  {
    matches = [
      {
        device.name = "~alsa_card.*"
      }
    ]
    actions = {
      update-props = {
        api.alsa.use-acp = true
        api.alsa.use-ucm = true
      }
    }
  }

  ### Disable S/PDIF Input/Output ###
  {
    matches = [
      {
        node.name = "~alsa_.*iec958-stereo"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]

monitor.alsa.rules = [
  ### HyperX Cloud II ###
  {
    matches = [
      {
        device.name = "alsa_card.usb-Kingston_HyperX_Virtual_Surround_Sound_00000000-00"
      }
    ]
    actions = {
      update-props = {
        device.nick = "HyperX Cloud II Audio"
        device.description = "HyperX Cloud II Audio"
        device.profile = "output:analog-stereo+input:analog-stereo"
      }
    }
  }
  {
    matches = [
      {
        node.name = "~alsa_.*usb-Kingston_HyperX_Virtual_Surround_Sound_00000000-00.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.nick = "HyperX Cloud II"
        node.description = "HyperX Cloud II Analog Stereo"
      }
    }
  }

  ### Sapphire RX 7800XT Nitro+ ###
  {
    matches = [
      {
        device.name = "alsa_card.pci-0000_0c_00.1"
      }
    ]
    actions = {
      update-props = {
        device.nick = "NVIDIA RTX 5060Ti HDMI/DP"
        device.description = "NVIDIA RTX 5060Ti HDMI/DP"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_0a_00.1.hdmi-stereo"
      }
    ]
    actions = {
      update-props = {
        node.nick = "TCL 65C655"
        node.description = "TCL 65C655 Digital Audio"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_0c_00.1.hdmi-stereo-extra1"
      }
    ]
    actions = {
      update-props = {
        node.nick = "BenQ RD320U"
        node.description = "BenQ RD320U Digital Audio"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_0c_00.1.hdmi-stereo-extra2"
      }
    ]
    actions = {
      update-props = {
        node.nick = "LG 27GP850-B"
        node.description = "LG 27GP850-B Digital Audio"
      }
    }
  }

  ### Realtek ALC1220 ###
  {
    matches = [
      {
        device.name = "alsa_card.pci-0000_0e_00.4"
      }
    ]
    actions = {
      update-props = {
        device.nick = "Realtek ALC1220 Audio"
        device.description = "Realtek ALC1220 Audio"
        device.profile = "output:analog-stereo+input:analog-stereo"
      }
    }
  }

  ### UGREEN BT501 - USB Dongle (AptX support) ###
  {
    matches = [
      {
        device.name = "alsa_card.usb-TaiYiLian_UGREEN-BT501_B850509B697A228EE689-02"
      }
    ]
    actions = {
      update-props = {
        device.nick = "UGREEN-BT501 AptX Audio"
        device.description = "UGREEN-BT501 AptX Audio"
        device.product.name = "UGREEN-BT501 AptX Audio"
      }
    }
  }
  {
    matches = [
      {
        node.name = "alsa_output.usb-TaiYiLian_UGREEN-BT501_B850509B697A228EE689-02.analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.description = "UGREEN-BT501 AptX Analog Stereo"
      }
    }
  }
]
