#!/bin/bash
# ~/.bash_profile
# Last Modified: Tue 08 Jan 2013 01:32:13 AM ICT

if [ -f ~/.bashrc ]; then
       source ~/.bashrc
fi

### START-Keychain ###
# Let re-use ssh-agent and/or gpg-agent between logins
keychain $HOME/.ssh/id_rsa
source $HOME/.keychain/$HOSTNAME-sh
source $HOME/.keychain/$HOSTNAME-sh-gpg
### END-Keychain ###

_byobu_sourced=1 . /usr/bin/byobu-launch
