#!/bin/bash
# ~/.bash_profile
# Last Modified: 05/12/2013 01:40 AM

export HOSTNAME=`hostname`

### START-Keychain ###
# Let re-use ssh-agent and/or gpg-agent between logins
keychain $HOME/.ssh/id_rsa
keychain $HOME/.ssh/google_compute_engine
source $HOME/.keychain/$HOSTNAME-sh
source $HOME/.keychain/$HOSTNAME-sh-gpg
### END-Keychain ###