#!/bin/bash
# ~/.bash_profile
# Last Modified: 05/12/2013 01:40 AM

### START-Keychain ###
# Let re-use ssh-agent and/or gpg-agent between logins
keychain $HOME/.ssh/id_rsa
source $HOME/.keychain/$HOSTNAME-sh
source $HOME/.keychain/$HOSTNAME-sh-gpg
### END-Keychain ###

_byobu_sourced=1 . /usr/bin/byobu-launch
