#!/bin/bash
# ~/.bashrc
# Last Modified: 05/12/2013 01:43 AM

# Some settings ----------------------------------------------------------------
ulimit -S -c 0                # Don't want any coredumps.
set -o notify                 # XXX
set -o noclobber              # XXX
set completion-ignore-case on # Complete things that have been typed
                              # in the wrong case

set visible-stats on          # When listing possible file completions,
                              # put / after directory names and * after programs

#set -o ignoreeof             # XXX
#set -o nounset               # XXX
#set -o xtrace                # Useful for debuging.
shopt -s cdspell              # Directory spelling
shopt -s cdable_vars
shopt -s checkhash
shopt -s checkwinsize
shopt -s sourcepath
shopt -s no_empty_cmd_completion
shopt -s cmdhist
shopt -s histappend
shopt -s histreedit
shopt -s histverify
shopt -s extglob              # Necessary for programmable completion.
stty -ixoff -ixon             # Fix C-S to freeze in vim

# Disable options:
shopt -u mailwarn
unset MAILCHECK               # Don't want my shell to warn me of incoming mail.

# bash history tweak
HISTCONTROL=ignoreboth:erasedups # ingore duplicates and spaces
HISTTIMEFORMAT='%F %T '

# don't append the following to history: consecutive duplicate
# commands, ls, bg and fg, and exit
HISTIGNORE='&:[bf]g:jobs:%1:%2:ls:ls *:cd:cd *:pwd:c:history:clear:exit'

# ------------------------------------------------------------------------------
# Test for an interactive shell.
if [[ $- != *i* ]] ; then
    # Shell is non-interactive.  Be done now!
    return
fi

# Colors -----------------------------------------------------------------------
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'

# when connecting to SSH, start or reattach screen session ---------------------
# if [ -n "$SSH_CONNECTION" ] && [ -z "$SCREEN_EXIST" ]; then
#   export SCREEN_EXIST=1
#  screen -DR
# fi

# Change the window title of X terminals ---------------------------------------
case ${TERM} in
    xterm*|*rxvt*|Eterm|aterm|kterm|gnome*|interix)
        PROMPT_COMMAND='echo -ne "\033]0;${PWD/$HOME/~}\007"'
        ;;
    screen)
        PROMPT_COMMAND='echo -ne "\033_${PWD/$HOME/~}\033\\"'
        ;;
esac

use_color=false
# ------------------------------------------------------------------------------
# Set colorful PS1 only on colorful terminals.
# dircolors --print-database uses its own built-in database
# instead of using /etc/DIR_COLORS.  Try to use the external file
# first to take advantage of user additions.  Use internal bash
# globbing instead of external grep binary.

safe_term=${TERM//[^[:alnum:]]/?}   # sanitize TERM
match_lhs=""
[[ -f $HOME/.dir_colors   ]] && match_lhs=" ${match_lhs}$(<$HOME/.dir_colors)"
[[ -f /etc/DIR_COLORS ]] && match_lhs=" ${match_lhs}$(</etc/DIR_COLORS)"
[[ -z ${match_lhs}    ]] \
    && type -P dircolors >/dev/null \
    && match_lhs=$(dircolors --print-database)
[[ $'\n'${match_lhs} == *$'\n'"TERM "${safe_term}* ]] && use_color=true

if ${use_color} ; then
    # Enable colors for ls, etc.  Prefer ~/.dir_colors #64489
    if type -P dircolors >/dev/null ; then
        if [[ -f $HOME/.dir_colors ]] ; then
            eval $(dircolors -b $HOME/.dir_colors)
        elif [[ -f /etc/DIR_COLORS ]] ; then
            eval $(dircolors -b /etc/DIR_COLORS)
        fi
    fi
    if [[ ${EUID} == 0 ]] ; then
        PS1='\[\033[01;31m\]\u\[\033[01;34m\] \W \[\033[00m\]\# \[\033[01;31m\]\$ \[\033[00m\]'
    else
        # PS1='\[\033[01;31m\]\@ \[\033[01;32m\]\u\[\033[01;31m\]@\[\033[01;34m\]\h-> \W\[\033[01;32m\] \$: \[\033[00m\]'
        PS1="\[\033[01;31m\]\t \[\033[01;32m\]\u\[\033[01;31m\]@\[\033[01;34m\]\h-> \W \#\[\033[01;32m\] \`if [ \$? = 0 ]; then echo \[\e[32m\]:\) \$: \[\033[00m\]; else echo \[\e[31m\]:\( \$: \[\033[00m\]; fi\`"
        # PS1="\e[0m[\[\033[01;31m\]\t\e[0m][\[\033[01;32m\]\u\[\033[01;31m\]@\[\033[01;34m\]\h\e[0m][\[\033[01;34m\]\W\e[0m] \#\[\033[01;32m\] \`if [ \$? = 0 ]; then echo \[\e[32m\]:\) \$: \[\033[00m\]; else echo \[\e[31m\]:\( \$: \[\033[00m\]; fi\`"
        # PS1="\e[0m[\[\033[01;34m\]\w\e[0m][\[\033[01;31m\]\t\e[0m]\n[\#][\[\033[01;32m\]\u\[\033[01;31m\]@\[\033[01;34m\]\h\e[0m]\[\033[01;32m\] \`if [ \$? = 0 ]; then echo \[\e[32m\]:\) \$: \[\033[00m\]; else echo \[\e[31m\]:\( \$: \[\033[00m\]; fi\`"
    fi
else
    if [[ ${EUID} == 0 ]] ; then
        # show root@ when we don't have colors
        PS1='\@ \u@\h \W \$ '
    else
        PS1='\@ \u@\h \w \$ '
    fi
fi

# Try to keep environment pollution down, EPA loves us.
unset use_color safe_term match_lhs

# source some bash files -------------------------------------------------------
if [ -f $HOME/.shell_env ]; then source $HOME/.shell_env; fi
if [ -f $HOME/.shell_functions ]; then source $HOME/.shell_functions; fi
if [ -f $HOME/.shell_aliases ]; then source $HOME/.shell_aliases; fi
if [ -f /etc/bash_completion ]; then source /etc/bash_completion; fi

# virtualenvwrapper
[[ -s /usr/local/bin/virtualenvwrapper.sh ]] && source /usr/local/bin/virtualenvwrapper.sh

# Realtime ~/.bash_history
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# End of ~/.bashrc